### ISSUE TITLE
跑不起来

### ISSUE THREAD

**Issue by KorciaSi** [vincentzyc/form-design-h5#1]

**Comment by vincentzyc** [comment]
需要配合另一个系统使用
See [form-design](https://github.com/vincentzyc/form-design).

**Comment by EmilyHOC** [comment]
请问你拖拽的时候有阴影问题吗，就是目标容器出现阴影

**Comment by vincentzyc** [comment]
> 请问你拖拽的时候有阴影问题吗，就是目标容器出现阴影

具体什么阴影呢？截图看看

**Comment by EmilyHOC** [comment]
![US9O 376S7$_1OXX$ FD QB](https://user-images.githubusercontent.com/27262265/72230646-d0852a80-35f1-11ea-8e3f-f720c0a9e4ce.png)
