### ISSUE TITLE
页面空白

### ISSUE THREAD

**Issue by 875279177** [vincentzyc/form-design-h5#24]
npm install 
npm run serve

  App running at:
  - Local:   http://localhost:9010 
  - Network: 

  Note that the development build is not optimized.
  To create a production build, run npm run build.

打开页面空白

<img width="216" alt="截屏2022-06-22 下午5 43 21" src="https://user-images.githubusercontent.com/6101740/174998338-7c737ca0-412b-4da8-9c84-86c7939fd6e2.png">

**Comment by vincentzyc** [comment]
需要配合另一个系统使用
See [form-design](https://github.com/vincentzyc/form-design).
